#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

[[ -f ~/.bashrc_alias ]] && . ~/.bashrc_alias

PS1='[\u@\h \W]\$ '

export GOPATH="/go"
export PATH="${GOPATH}/bin:${PATH}"
